### ISSUE TITLE
Support PowerShell 1.0/2.0

### ISSUE THREAD

**Issue by flcdrg** [flcdrg/PowerShellWixExtension#11]
Need to build on a machine that has System.Management.Automation, Version=1.0.0.0

(Windows 7?)

**Comment by bergmeister** [comment]
Since PowerShell 2.0 has been deprecated by now (see [here](https://blogs.msdn.microsoft.com/powershell/2017/08/24/windows-powershell-2-0-deprecation/)), I think this issue can be closed.

**Comment by flcdrg** [comment]
Yeah, I think you're right.

**Comment by publicst** [comment]
Hi, This may be trivial wix question, but I do have situation where I need to install to clean Windows 7 (Which has Powershell 2.0). In this case, I would like to skip powershell:Script. I would not want to use Condition as it would terminate the installation. Would you have some way to skip the execution under certain condition?

**Comment by flcdrg** [comment]
I'm not sure myself. I'd go searching for answers around "wix conditional custom actions". Maybe you could achieve the desired result by having another custom action run first and set a property that is then used to decide whether to run the PowerShell action or not? I'm just thinking out loud, that may not be possible.

**Comment by bergmeister** [comment]
Just make the decision inside the ps script using `$PSVersionTable` properties

**Comment by publicst** [comment]
I have attempted to avoid PSVersionTable using 
```If($PSVersionTable.PSVersion.Major -gt 2)```

However, msi log tells me on Windows 7 (Does not occur on Windows 10)
```
Executing PowerShell script:
If($PSVersionTable.PSVersion.Major -gt 2) {MY_PS_SCRIPT}
PowerShell terminating error, returning Failure
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at PowerShellActions.PowerShellTask..ctor(String script, Session session)
   at PowerShellActions.CustomActions.ScriptsDeferred(Session session, String deferredProperty)
CustomAction PowerShellScriptsDeferred returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

Would I be doing something wrong here?
