### ISSUE TITLE
PowerShell script doesn't run correctly when calling msiexec.exe

### ISSUE THREAD

**Issue by eddex** [flcdrg/PowerShellWixExtension#24]
I try to uninstall another software during my installation process using a PowerShell script.

My Install sequence looks like this:
```xml
<InstallExecuteSequence>
    <Custom Action="PowerShellScriptsDeferred" After="RemoveFiles"></Custom>
    <ScheduleReboot After="InstallFinalize"/>
</InstallExecuteSequence>
```

And my Script looks like this:
```xml
<powershell:Script Id="UninstallOldVersion">
	<![CDATA[
		$id = {SOME-GUID-XXX000}
		msiexec.exe /norestart /passive /uninstall $id | Out-Null
	]]>
</powershell:Script>
```

But when I run my installer, the msiexec command isn't executed properly. Instead of uninstalling the software it just opens the help window (as if the command is run without any parameters).

Any suggestions?

**Comment by eddex** [comment]
By replacing the PowerShell code with this,
```powershell
Start-Process C:\Windows\System32\msiexec.exe -ArgumentList "/norestart /passive /uninstall {SOME-GUID-XXX000}" -wait
```

I got it running. Well kinda.. The installer is opened and exits with code 0 (success) but the software is not uninstalled.

**Comment by eddex** [comment]
The command not working propperly was due to the fact that Windows doesn't permit 2 installers to run at the same time. SO what I was trying to do is not possible like this.

However, I'd assume my code from the fist comment would run like that. Or am I wrong here?

**Comment by flcdrg** [comment]
The line `$id = {SOME-GUID-XXX000}` looks odd. I wonder if you put the value in quotes whether that would help?

**Comment by eddex** [comment]
> The line `$id = {SOME-GUID-XXX000}` looks odd. I wonder if you put the value in quotes whether that would help?

You're right,  if I put the GUID in quotes, `msiexec` is started as expected (and then crashed due to the issue with running 2 installers at the same time obviously). I works without quotes in a normal PowerShell script though.

Thanks for your help :)
