### ISSUE TITLE
KeyNotFoundException thrown when running an inline Script without a File element

### ISSUE THREAD

**Issue by dhudec** [flcdrg/PowerShellWixExtension#5]
I was attempting to run an inline script (only) without deploying a ps1 file. When running the installer, the log output of msiexec showed a KeyNotFoundException was thrown from CustomActions.FilesDeferred. 

Moving the contents of this inline script to a file and adding a <powershell:File> element resolved the issue.

**Comment by flcdrg** [comment]
Interesting.. was there a stack trace you can post?

**Comment by dhudec** [comment]
Sorry I didn't post this earlier - I wanted to report the issue before I forgot and didn't have the stack trace available. I just reverted back to using only an inline script and was able to reproduce the error. Here's the stack trace:

<pre>MSI (s) (80:24) [20:02:16:250]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI5B51.tmp, Entrypoint: PowerShellFilesDeferred
SFXCA: Extracting custom action to temporary directory: C:\Users\DREW~1.HUD\AppData\Local\Temp\MSI5B51.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action PowerShellActions!PowerShellActions.CustomActions.PowerShellFilesDeferred
PowerShellFilesDeferred start
PowerShell terminating error, returning Failure
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PowerShellActions.CustomActions.FilesDeferred(Session session, String deferredProperty)
CustomAction PowerShellFilesDeferred returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)</pre>

Not sure if this will be of any help, but here's the rest of the relevant portion of the msiexec verbose log:
<pre>Calling custom action PowerShellActions!PowerShellActions.CustomActions.PowerShellScriptsImmediate
Action ended 20:02:13: PowerShellScriptsImmediate. Return value 1.
MSI (s) (80:FC) [20:02:13:616]: Doing action: PowerShellScriptsDeferred
Action start 20:02:13: PowerShellScriptsDeferred.
Action ended 20:02:13: PowerShellScriptsDeferred. Return value 1.
MSI (s) (80:FC) [20:02:13:622]: Doing action: PowerShellScriptsElevatedImmediate
Action start 20:02:13: PowerShellScriptsElevatedImmediate.
MSI (s) (80:B0) [20:02:13:631]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI510E.tmp, Entrypoint: PowerShellScriptsElevatedImmediate
SFXCA: Extracting custom action to temporary directory: C:\Users\DREW~1.HUD\AppData\Local\Temp\MSI510E.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action PowerShellActions!PowerShellActions.CustomActions.PowerShellScriptsElevatedImmediate
Adding PostInstallScript to CustomActionData
MSI (s) (80!24) [20:02:13:878]: PROPERTY CHANGE: Adding PowerShellScriptsElevatedDeferred property. Its value is 'PostInstallScript=DQAKACAAIAAgACAAIAAgACMAYQBuAHkAIABzAGMAcgBpAHAAdAAgAGMAYQBuACAAZwBvACAAaABlAHIAZQANAAoAIAAgACAAIAAgACAA'.
Action ended 20:02:13: PowerShellScriptsElevatedImmediate. Return value 1.
MSI (s) (80:FC) [20:02:13:893]: Doing action: PowerShellScriptsElevatedDeferred
Action start 20:02:13: PowerShellScriptsElevatedDeferred.
Action ended 20:02:13: PowerShellScriptsElevatedDeferred. Return value 1.</pre>

**Comment by flcdrg** [comment]
Thanks.. that is helpful. I'll see if I can fix this soon.

David

**Comment by flcdrg** [comment]
I have published a new version here - https://www.nuget.org/packages/PowerShellWixExtension/2.0.0-beta1.

It should have fixed this issue. Let me know if how it goes!
