### ISSUE TITLE
compiler error: D:\dev\git\PowerShellWixExtension\PowerShellLibrary\Library.wxs(59): error LGHT0094: Unresolved reference to symbol 'WixAction:InstallExecuteSequence/PowerShellScriptsDeferred' in section 'Fragment:'. [FakePathToMyWixProj.wixproj]

### ISSUE THREAD

**Issue by jzajac2** [flcdrg/PowerShellWixExtension#6]
I am getting an error when I only declare the PowerShellScriptsElevatedDeferred custom action in my Product:

```
    <InstallExecuteSequence>
      <Custom Action="PowerShellScriptsElevatedDeferred" After="InstallFiles">NOT Installed</Custom>
    </InstallExecuteSequence>
```

The error is: 

```
(Link target) -> 
 D:\dev\git\PowerShellWixExtension\PowerShellLibrary\Library.wxs(59): error LGHT0094: Unresolved reference to symbol 'WixAction:InstallExecuteSequence/PowerShellScriptsDeferred' in section 'Fragment:'. [FakePathToMyWixProj.wixproj]
```

Is it by design that I have to declare all four? I figured your documentation was just showing all four for demo purposes, however it seems I'm wrong?

**Comment by flcdrg** [comment]
You're right in that the documentation was for demo purposes, so I think this is a bug - you should be able to pick just which ones you want. I think this is related to #5

**Comment by flcdrg** [comment]
Just reviewed the code, and turns out this is by design. 

I wanted to allow the end-user (Wix developer) to be able to override when the actions take place. The only way I could figure out how to do this was to let the user add in the InstallExecuteSequence custom actions. If there's a better way to do this, happy to consider it.

**Comment by flcdrg** [comment]
Actually I figured out a way to do this.. Try the latest beta out. You don't need to specify the custom actions at all now, unless you need to override the default sequence.
