### ISSUE TITLE
Issue with PowerShellScriptsDeferred Action

### ISSUE THREAD

**Issue by varun7447** [flcdrg/PowerShellWixExtension#8]
The powershell script is executed before the InstallFiles.

      <Custom Action="PowerShellScriptsDeferred" After="InstallFiles">NOT Installed</Custom>
      <Custom Action="PowerShellScriptsElevatedDeferred" After="InstallFiles">NOT Installed</Custom>
      <Custom Action="PowerShellFilesDeferred" After="InstallFiles">NOT Installed</Custom>
      <Custom Action="PowerShellFilesElevatedDeferred" After="InstallFiles">NOT Installed</Custom>

<powershell:File Id="PSFile1" File="[#PGSetupPs1]" Arguments="-LogDir &quot;C:\TEMP&quot; -InstallDir &quot;[POSTGRESFOLDER]&quot; -Hostname [HOSTNAME] -Username [USERNAME] -Port [PORT] -DBName [DBNAME] -ServiceName $(var.PostgresServiceName) -Password [PASSWORD]" Elevated="yes" />

PGSetupPS1 will call a install file that exists in the installation folder. But the PGSetupPS1 is executed before the install file.

**Comment by flcdrg** [comment]
Is this using the latest preview release?

Do you have a log file I can look at?

**Comment by varun7447** [comment]
I am using the stable version 1.9. There is no log file.

**Comment by flcdrg** [comment]
You can create a log file by launching your msi with msiexec. `msiexec /?` shows all the options available (lots of different options for how much logging you want to get) eg.

`msiexec myinstaller.msi /l*v install.log`

Should produce a very verbose install log. You can review that to find when the actions are being performed and if there are any other errors that might be causing issues.

**Comment by varun7447** [comment]
Thanks for the command, my msi is part of a bundle exe. But install files that i am looking for should be  part of the msi file but not with bundle.exe. Will provide the log file soon,.,

**Comment by varun7447** [comment]
Attached is the log file 
[DBInitializer.zip](https://github.com/flcdrg/PowerShellWixExtension/files/294036/DBInitializer.zip)

**Comment by varun7447** [comment]
Does the extension require powershell 3.0 ?

**Comment by flcdrg** [comment]
Yes, the current distribution requires PowerShell 3.0 or above.

**Comment by varun7447** [comment]
Do you recommend any other alternatives?

**Comment by flcdrg** [comment]
You can always build the extension locally on your machine against the 1.0.0.0 version. Pretty sure there's nothing code-wise that's dependent on the 3.0.0.0 version.
