### ISSUE TITLE
Adding multiple arguments

### ISSUE THREAD

**Issue by RafDelgadoUK** [flcdrg/PowerShellWixExtension#9]
Hi There,

I have a powershell script which I would like to pass wix properties to. The script has multiple parameters and I'm working how you add multiples in the powershell:file attribute?

<powershell:File Id="PSFile1" File="[#TestPs1]" Arguments="&quot;[FirstAttribute]&quot; 1" />

**Comment by flcdrg** [comment]
Have you tried something like this?

    <powershell:File Id="PSFile1" File="[#TestPs1]" Arguments="&quot;[PropertyOne]&quot; &quot;[PropertyTwo]&quot;"/>

(I'm just typing this without testing it)

**Comment by RafDelgadoUK** [comment]
Thanks for the response, I managed to do it via single quotations. 

<powershell:File Id="PSFile1" File="[#InstallPS1]Arguments="'[PROPERTY1]' '[PROPERTY2]''" Elevated="yes"/>

Couple of things picked up though, the property themselves are set to hidden and secure so shouldn't show up in the log. When checking the log you van see the arguments in plain text (even though the rest of the log has the properties hidden. 

Other thing noticed was that it seems to run powershell in x86 as had error on loading a com object which is x64. Managed to get around it by running an invoke. Is there a way to get it to run in x64 instead?

**Comment by flcdrg** [comment]
Interesting about the properties and logging. Not sure if I can do anything about that. I'll create a separate issue to track it in case it is possible (#10)

x64 has been mentioned before in #4. Not implemented yet though (and not sure when it will be)

**Comment by RafDelgadoUK** [comment]
Thanks David, just observations but thought worth mentioning.
